## test config file for shotgun metagenomics pipeline!

raw_seq_in: 'batches_combined' ## need to use symlink bc container paths will break, this worked!! 
## has to be a .csv or it will break
metadata_file: 'data/madisVer_shotgun_metaG_batchesComb.csv'
filter_to_fasta: '/scratch/alpine/mapgar@xsede.org/outside_refs/hg38.p14.fa'
## database file paths - will eventually have the installation in the pipeline but for now will need to be pre-installed
metaphlan_db: '/pl/active/LozuponeLab/homi_databases/humann/metaphlan/'
## the name of the metaphlan index installed - MUST match the version of humann/metaphlan installed!!
metaphlan_index_name: 'mpa_vJun23_CHOCOPhlAnSGB_202307'
chocophlan_db: '/pl/active/LozuponeLab/homi_databases/humann/chocophlan/'
uniref_db: '/pl/active/LozuponeLab/homi_databases/humann/uniref/'
utility_mapping_db: '/pl/active/LozuponeLab/homi_databases/humann/utility_mapping/'

